name: CI
on: [push]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master

      - name: Setup Elm
        uses: jorelali/setup-elm@v1
        with:
          elm-version: 0.19.1

      - name: Build
        run: elm make src/test.elm
